var topping = {
    "cheese": "C",
    "pepperoni": "P",
    "sausage": "S",
    "italian sausage": "S",
    "sliced italian sausage": "Sb",
    "beef": "B",
    "steak": "Pm",
    "philly steak": "Pm",
    "ham": "H",
    "bacon": "K",
    "salami": "Sa",
    "chicken": "Du",
    "premium chicken": "Du",
    "anchovy": "A",
    "anchovies": "A",
    "american cheese": "Ac",
    "cheddar": "E",
    "cheddar cheese": "E",
    "feta": "Fe",
    "feta cheese": "Fe",
    "parmesan": "Cs",
    "parmesan cheese": "Cs",
    "parmesan asiago": "Cs",
    "shredded parmesan asiago": "Cs",
    "banana peppers": "Z",
    "olive": "R",
    "olives": "R",
    "black olive": "R",
    "black olives": "R",
    "green pepper": "G",
    "green peppers": "G",
    "jalapenos": "J",
    "jalapeno peppers": "J",
    "mushroom": "M",
    "mushrooms": "M",
    "pineapple": "N",
    "onion": "O",
    "onions": "O",
    "red pepper": "Rr",
    "red peppers": "Rr",
    "roasted red pepper": "Rr",
    "roasted red peppers": "Rr",
    "spinach": "Si",
    "tomato": "Td",
    "tomatoes": "Td",
    "diced tomato": "Td",
    "diced tomatoes": "Td",
    "hot sauce": "Ht",
    "alfredo": "Xf",
    "alfredo sauce": "Xf",

    // I'm pretty sure this is only a sandwich topping
    "provolone": "Pv",
    "shredded provolone": "Pv",
    "shredded provolone cheese": "Pv",
}

// Later, we can nest another dictionary for crust types or something
var size = {
    "small": "10SCREEN",
    "medium": "12SCREEN",
    "large": "14SCREEN",
    "extra large": "16SCREEN",
    "XL": "16SCREEN",
}

module.exports = {
    "lol": "lol",
    "topping": topping,
    "size": size
}